# Generated by Django 2.1.7 on 2019-12-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan_T',
            fields=[
                ('Vlan_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
    ]
